//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bajaj.Dinesh.Biller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bajaj.Dinesh.Biller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap account_22 {
            get {
                object obj = ResourceManager.GetObject("account_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_invoice_22 {
            get {
                object obj = ResourceManager.GetObject("add_invoice_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_item_22 {
            get {
                object obj = ResourceManager.GetObject("add_item_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_payment_22 {
            get {
                object obj = ResourceManager.GetObject("add_payment_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backup_22 {
            get {
                object obj = ResourceManager.GetObject("backup_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_22 {
            get {
                object obj = ResourceManager.GetObject("calculator_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check_24 {
            get {
                object obj = ResourceManager.GetObject("check_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configuration_22 {
            get {
                object obj = ResourceManager.GetObject("configuration_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer_22 {
            get {
                object obj = ResourceManager.GetObject("customer_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [UnitOfMeasurement] (
        ///  [ID] int NOT NULL  IDENTITY (1,1)
        ///, [UnitName] nvarchar(30) NOT NULL
        ///);
        ///GO
        ///CREATE TABLE [Items] (
        ///  [ID] int NOT NULL  IDENTITY (1,1)
        ///, [NAME] nvarchar(70) NOT NULL
        ///, [UoMID] int NOT NULL
        ///, [UnitPrice] money NOT NULL
        ///);
        ///GO
        ///CREATE TABLE [FirmDetails] (
        ///  [FirmName] nvarchar(70) NOT NULL
        ///, [Address] nvarchar(100) NULL
        ///, [PhoneNumbers] nvarchar(100) NULL
        ///);
        ///GO
        ///CREATE TABLE [FinancialYear] (
        ///  [StartYear] int NOT NULL
        ///, [BooksStartDate] datetime NOT NULL        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseScript {
            get {
                return ResourceManager.GetString("DatabaseScript", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete_22 {
            get {
                object obj = ResourceManager.GetObject("delete_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explore_24 {
            get {
                object obj = ResourceManager.GetObject("explore_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoice_22 {
            get {
                object obj = ResourceManager.GetObject("invoice_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoice_32 {
            get {
                object obj = ResourceManager.GetObject("invoice_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16_1 {
            get {
                object obj = ResourceManager.GetObject("refresh_16_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16_2 {
            get {
                object obj = ResourceManager.GetObject("refresh_16_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_16 {
            get {
                object obj = ResourceManager.GetObject("search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
